engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
    checks:
      compatible-vendor-prefixes:
        enabled: false
      important:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "**"
exclude_paths:
- "parrot-manager/src/main/resources/webapp/app/mocks.js"
