engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  markdownlint:
    enabled: true
exclude_paths:
- "parrot-manager/src/main/resources/webapp/app/mocks.js"
