language: java
matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.2
node_js:
  - "9"
before_install:
  - npm i npm@^4 -g
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y fakeroot; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpm; fi
install: true
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then     mvn clean package -Pjar,mac,java8;  fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   mvn clean package -Pjar,linux;      fi
