language: java
matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk9
    - os: osx
      osx_image: xcode9.2
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_install:
  - npm i npm@^4 -g
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y fakeroot; fi
install: true
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then     mvn clean package -Pjar,windows-standalone,mac,java8;     fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   mvn clean package -Pjar,windows-standalone,linux;         fi
