language: java
dist: trusty
jdk:
  - oraclejdk8
  - oraclejdk9
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
before_install:
  - npm i npm@^4 -g
os:
  - linux
  - osx
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then     mvn clean package -Pjar,windows-standalone,mac     fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then   mvn clean package -Pjar,windows-standalone,linux   fi
